FROM python:3.11

WORKDIR /app

COPY requirements.txt /tmp/requirements.txt

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY ./app /app

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
